<a href="https://colab.research.google.com/github/geogesarmani-sudo/king_git/blob/main/S13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
print(os.getcwd())   # montre le dossier où Colab exécute ton code

/content

In [3]:
# Exercice1
import pandas as pd
ONU=pd.read_csv('monde_2023_academy.csv')
ONU.head()

Nombre de pays africains : 53

In [4]:
print(ONU.shape)

(190, 7)

In [5]:
print(ONU.dtypes)

country       object
iso3          object
continent     object
year           int64
pop           object
lifeExp      float64
gdpPercap    float64
dtype: object

In [6]:
# C'est la colonne Pop, car elle contient des entiers et non des caractères ou chaine de caractère
print(ONU.describe())
# On remarque la moyenne est plus conséquante que la médiane, et que la moyenne ne represente pas réellement la situation individuelle de chaque pays tant dis que la médiane ci

         year     lifeExp      gdpPercap
count   190.0  185.000000     185.000000
mean   2023.0   73.247200   17804.797715
std       0.0    7.062549   23957.069605
min    2023.0   54.462000     193.007146
25%    2023.0   67.689000    2477.978455
50%    2023.0   73.720000    7820.103638
75%    2023.0   78.580000   22888.275089
max    2023.0   85.511000  128678.189943

In [7]:
ONU.isnull().sum()

country      0
iso3         0
continent    0
year         0
pop          0
lifeExp      5
gdpPercap    5
dtype: int64

In [8]:
ONU.isnull().mean() * 100
# D'après ces résultats, comme le pourcentage de la colonne lifeExp et gdpPercap sont inférieur à 5%, on peut procéder par la suppression des lignes concernées sans trop de perte!

country      0.000000
iso3         0.000000
continent    0.000000
year         0.000000
pop          0.000000
lifeExp      2.631579
gdpPercap    2.631579
dtype: float64

In [9]:
ONU = ONU.dropna(subset=["lifeExp", "gdpPercap"])

In [10]:
ONU.isnull().sum()

country      0
iso3         0
continent    0
year         0
pop          0
lifeExp      0
gdpPercap    0
dtype: int64

In [11]:
ONU.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
185    False
186    False
187    False
188    False
189    False
Length: 180, dtype: bool

In [12]:
print(ONU.duplicated().sum())

5

In [13]:
ONU = ONU.drop_duplicates()

In [14]:
print(ONU.duplicated().sum())

0

In [15]:
ONU[ONU["iso3"] == "COG"]
# on constate que le congo dans country est  écrit en miniscule

    country iso3 continent  year      pop  lifeExp    gdpPercap
47   congo   COG    Africa  2023  6182885   65.772  2477.978455

In [16]:
# Corriger toute la colonne
ONU.loc[ONU["iso3"] == "COG", "country"] = "Congo"

In [17]:
# La recherche directe est maintenant fonctionnelle
print(ONU[ONU["country"] == "Congo"])

   country iso3 continent  year      pop  lifeExp    gdpPercap
47   Congo  COG    Africa  2023  6182885   65.772  2477.978455

In [18]:
ONU['pop']=(ONU['pop'].astype(str).str.replace(r'\D', '', regex=True).astype(int))

In [19]:
print(ONU['pop'].dtype)
print(ONU['pop'].head())

int64
0       458949
1    336806231
2     11331265
3     10407351
4     23025776
Name: pop, dtype: int64

In [20]:
# Exercice 7
# Question a
Extrait_ONU= ONU[["country", "continent", "lifeExp"]]
print(Extrait_ONU)

                  country continent  lifeExp
0                  Brunei      Asia   75.327
1           United States  Americas   79.304
2      Dominican Republic  Americas   73.720
3                  Greece    Europe   81.857
4            Burkina Faso    Africa   61.092
..                    ...       ...      ...
185      Marshall Islands   Oceania   66.945
186              Slovakia    Europe   78.341
187         Guinea-Bissau    Africa   64.085
188               Burundi    Africa   63.651
189  United Arab Emirates      Asia   82.909

[175 rows x 3 columns]

In [21]:
# Question b
print(ONU.head())
print(ONU[['country','pop']].head())

              country iso3 continent  year        pop  lifeExp     gdpPercap
0              Brunei  BRN      Asia  2023     458949   75.327  32962.906453
1       United States  USA  Americas  2023  336806231   79.304  81236.427600
2  Dominican Republic  DOM  Americas  2023   11331265   73.720  10717.627671
3              Greece  GRC    Europe  2023   10407351   81.857  22888.275089
4        Burkina Faso  BFA    Africa  2023   23025776   61.092    882.689810
              country        pop
0              Brunei     458949
1       United States  336806231
2  Dominican Republic   11331265
3              Greece   10407351
4        Burkina Faso   23025776

In [22]:
# Question c
print(ONU[['country','pop']].loc[ONU['pop'] > 10**8 ].sort_values(by='pop', ascending= False))

                          country         pop
135                         China  1410710000
1                   United States   336806231
170                     Indonesia   281190067
61                       Pakistan   247504495
94                        Nigeria   227882945
128                        Brazil   211140729
157                        Russia   143826130
63                         Mexico   129739759
102                      Ethiopia   128691692
11                          Japan   124516650
24                    Philippines   114891199
69                          Egypt   114535772
178  Democratic Republic of Congo   105789731
155                       Vietnam   100352192

In [23]:
extrait_1 = ONU.loc[ONU['continent']=='Africa',['country','gdpPercap']]
print(extrait_1)

                          country     gdpPercap
4                    Burkina Faso    882.689810
5                         Senegal   1715.605653
18                     Mauritania   2081.174684
19                        Morocco   3741.713079
21                       Zimbabwe   1624.047646
22                          Kenya   1941.498220
25                     Madagascar    513.903637
30                         Guinea   1639.120355
32                          Niger    642.937918
33                           Chad    680.639878
34                     Seychelles  17879.239655
40              Equatorial Guinea   6558.376822
42                        Namibia   4168.285136
47                          Congo   2477.978455
49                         Malawi    667.362557
52                           Mali    879.497943
56          Sao Tome and Principe   2612.890961
62                       Cameroon   1689.847355
69                          Egypt   3456.789685
71                          Benin   1394.177399
74                        Tunisia   3977.695166
76                          Ghana   2260.287345
79                        Lesotho    885.167125
85                           Togo    985.697512
88                          Sudan   2184.670787
94                        Nigeria   1592.111036
95                     Cape Verde   4953.280729
96                         Angola   2305.392499
102                      Ethiopia   1272.016282
104                  South Africa   5976.385909
109                        Gambia    867.323422
111                      Eswatini   3736.557030
112                      Botswana   7820.103638
118                     Mauritius  11530.182094
124                         Gabon   8256.690765
129                       Somalia    636.202683
133      Central African Republic    495.978897
136                        Rwanda   1010.268942
143                        Uganda   1012.665932
145                       Comoros   1590.312378
147                        Zambia   1358.940287
150                         Libya   6911.316617
153                       Algeria   5196.654386
159                 Cote d'Ivoire   2528.065957
160                      Tanzania   1188.248739
162                    Mozambique    613.185662
178  Democratic Republic of Congo    627.502182
184                       Liberia    788.635637
187                 Guinea-Bissau    913.214965
188                       Burundi    193.007146

In [24]:
nb_pays_africains = extrait_1.count()
print(nb_pays_africains)
# Cher coordo, je me retrouve avec 50 pays Africain

country      50
gdpPercap    50
dtype: int64

In [26]:
# la moyenne
print(extrait_1['gdpPercap'].mean())

2818.3107718665087

In [27]:
# la médiane
print(extrait_1['gdpPercap'].median())

1631.5840002398545

In [28]:
# deuxième methode
print(extrait_1.describe())

          gdpPercap
count     50.000000
mean    2818.310772
std     3233.148243
min      193.007146
25%      883.309139
50%     1631.584000
75%     3666.615194
max    17879.239655

In [30]:
# ça confirme une répartiton très asymétrique autrement dit quelques pays riches tirent la moyenne vers le haut
# les pays qui augmentés la moyenne
extrait_1 = ONU.loc[ONU['continent']=='Africa',['country','gdpPercap']].sort_values(by='gdpPercap',ascending=False).head(10)
print(extrait_1)

               country     gdpPercap
34          Seychelles  17879.239655
118          Mauritius  11530.182094
124              Gabon   8256.690765
112           Botswana   7820.103638
150              Libya   6911.316617
40   Equatorial Guinea   6558.376822
104       South Africa   5976.385909
153            Algeria   5196.654386
95          Cape Verde   4953.280729
42             Namibia   4168.285136

In [31]:
# Exercice 9
# Moyenne et écart-type pour l'Afrique
afrique = ONU.loc[ONU["continent"] == "Africa", "lifeExp"]
print("Afrique - Moyenne :", afrique.mean())
print("Afrique - Écart-type :", afrique.std())

# Moyenne et écart-type pour l'Europe
europe = ONU.loc[ONU["continent"] == "Europe", "lifeExp"]
print("Europe - Moyenne :", europe.mean())
print("Europe - Écart-type :", europe.std())
# En Europe, l’écart‑type est faible , la moyenne reflète bien la réalité.

# En Afrique, l’écart‑type est plus fort , la moyenne cache des inégalités entre pays.

Afrique - Moyenne : 65.57486
Afrique - Écart-type : 5.18927763055117
Europe - Moyenne : 79.81779487179486
Europe - Écart-type : 3.485239395081154

In [34]:
# Exercice 10
extrait_2 = ONU.loc[(ONU["continent"] == "Africa") & (ONU["iso3"].isin(["COG", "COD"])),["country", "iso3", "gdpPercap","lifeExp","pop"]]

print(extrait_2)
#  L’évolution dans le temps révèle que les deux Congo ne sont pas seulement proches aujourd’hui, mais qu’ils ont progressé ensemble et que leurs écarts se sont atténués.

                          country iso3    gdpPercap  lifeExp        pop
47                          Congo  COG  2477.978455   65.772    6182885
178  Democratic Republic of Congo  COD   627.502182   61.895  105789731

In [37]:
# Exercice 11
# Moyenne simple : chaque pays pèse pareil
moyenne_simple = ONU["lifeExp"].mean()

# Moyenne pondérée par la population
moyenne_ponderee = (ONU["lifeExp"] * ONU["pop"]).sum() / ONU["pop"].sum()

print(f"Moyenne simple : {moyenne_simple:.2f}")
print(f"Moyenne pondérée : {moyenne_ponderee:.2f}")
#  La moyenne pondérée est plus représentative de ce que vit “l’habitant moyen” de la planète.

Moyenne simple : 73.16
Moyenne pondérée : 73.73

In [38]:
# Exercice 12
correlation = ONU["gdpPercap"].corr(ONU["lifeExp"])
print(f"Corrélation : {correlation:.2f}")

# Pays atypique parmi les riches (PIB > 20 000 $)
riches = ONU[ONU["gdpPercap"] > 20000]
atypique = riches.sort_values(by="lifeExp").head(1)
print(atypique[["country", "gdpPercap", "lifeExp"]])
# Non, une corrélation forte ne prouve pas la causalité. D'autres facteurs (accès aux soins, éducation, stabilité politique, nutrition) peuvent expliquer les deux variables simultanément

Corrélation : 0.69
    country     gdpPercap  lifeExp
175  Guyana  20313.718421    70.18

In [ ]:
# Exercice 13
# Ce fichier contient des informations sur 190 pays en 2023. L’espérance de vie moyenne par pays est de 73,16 ans, mais si on tient compte du nombre d’habitants, elle monte à 73,73 ans. En Afrique, la moyenne est de 65,6 ans avec un écart‑type de 5,2 ans, ce qui veut dire que les pays sont assez différents entre eux. En Europe, la moyenne est plus haute, 79,8 ans, et l’écart‑type plus petit, 3,5 ans, donc les pays sont plus proches les uns des autres. Pour le PIB par habitant en Afrique, la moyenne est de 2 818 $, mais la médiane n’est que de 1 632 $, ce qui montre un biais : quelques pays riches tirent la moyenne vers le haut. On voit aussi une corrélation de 0,69 entre richesse et espérance de vie, ce qui veut dire que les pays plus riches vivent en général plus longtemps. Enfin, certains pays comme les Seychelles ou Maurice sont des valeurs aberrantes, car leur PIB est beaucoup plus haut que celui de leurs voisins.